env:
  browser: true
  commonjs: true
  node: true
extends: 'google'
parserOptions:
  ecmaVersion: 9
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi: 2
  no-debugger: 2
  comma-dangle:
    - error
    - arrays: "never"
      objects: "never"
      imports: "always-multiline"
      exports: "always-multiline"
      functions: "always-multiline"
  no-console: 2
  space-before-blocks: 0
  no-unused-vars:
    - error
    - vars: all
      args: all
      ignoreRestSiblings: true
  no-unused-expressions: 2
  no-useless-computed-key: 2
  no-use-before-define: 2
  no-useless-call: 2
  no-useless-concat: 2
  no-useless-constructor: 2
  no-useless-rename: 2
